version: '3.7'

services:
  frontend:
    build:

      context: ./frontend  # Вказуємо на папку frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app

    command: npm start

    networks:
      - app_network

  backend:
    build:
      dockerfile: ./Dockerfile
      context: ./backend  # Вказуємо на папку backend
    command: /bin/bash -c "alembic upgrade head&& uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - DATABASE_URL=postgresql://username:password@db:5433/nudges
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nudges
    ports:
      - "5434:5432"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:

    driver: bridge
