
services:
  frontend:
    build:
      dockerfile: ./Dockerfile
      context: ./frontend  # Вказуємо на папку frontend
    ports:
      - "3000:80"
    volumes:
      - .:/app
        - /app/node_modules
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    networks:
      - app_network



  backend:
    build:
      dockerfile: ./Dockerfile
      context: ./backend  # Вказуємо на папку backend
    command: /bin/sh -c "alembic upgrade head&& uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    networks:
      - app_network


  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nudges
    ports:
      - "5434:5432"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
