"""update_colum_phone

Revision ID: 9651cf91432c
Revises: d51a76c8cf5e
Create Date: 2024-12-06 11:30:42.460966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9651cf91432c'
down_revision: Union[str, None] = 'd51a76c8cf5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('phone', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'sessions', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='unique')
    op.drop_column('sessions', 'phone')
    # ### end Alembic commands ###
