"""add hash_cod_column

Revision ID: 4c28e4178990
Revises: 9651cf91432c
Create Date: 2024-12-06 13:47:57.198230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c28e4178990'
down_revision: Union[str, None] = '9651cf91432c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('hash_cod', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'hash_cod')
    # ### end Alembic commands ###
